version: '3.8'

services:
#  app:
#    build:
#      context: .
#      dockerfile: docker/Dockerfile
#    container_name: focus-flow-gateway-api
#    ports:
#      - '${GATEWAY_PORT}:${GATEWAY_PORT}'
#    environment:
#      - SERVER_PORT=${GATEWAY_PORT}
#      - KEYCLOAK_URL=http://localhost:${KEYCLOAK_PORT}
#      - KEYCLOAK_CLIENT_ID=${KEYCLOAK_CLIENT_ID}
#      - KEYCLOAK_CLIENT_SECRET=${KEYCLOAK_CLIENT_SECRET}
#    env_file:
#      - .env

  keycloak-db:
    image: postgres:17
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - keycloak-db-data:/var/lib/postgresql/data
    ports:
      - "5212:5432"
    env_file:
      - .env

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-db:5432/${POSTGRES_DB}
      KC_DB_USERNAME: ${POSTGRES_USER}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_HOSTNAME: localhost
    ports:
      - "${KEYCLOAK_PORT}:8080"
    depends_on:
      - keycloak-db
    command: [ "start-dev", "--import-realm" ]
    env_file:
      - .env
  grafana:
    build: './config/grafana'
    ports:
      - "3353:3000"
    volumes:
      - ./grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      monitoring:
        aliases:
          - grafana
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus:/prometheus
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      monitoring:
        aliases:
          - prometheus
networks:
  monitoring:
volumes:
  keycloak-db-data: