spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUE_URI}
          jwk-set-uri: http://localhost:4216/realms/spring-microservices-security-realm/protocol/openid-connect/certs  # Добавьте этот параметр
  cloud:
    gateway:
      default-filters:
        - TokenRelay
        - RemoveRequestHeader=Cookie  # Защита от CSRF
      routes:
        - id: task_service
          uri: ${TASK_SERVICE_URL}
          predicates:
            - Path=/api/projects/**,/api/tasks/**,/api/task-state/**,/api/tasks-states/**

        - id: habit_service
          uri: ${HABIT_SERVICE_URL}
          predicates:
            - Path=/api/habits/**,/api/habit-logs/**

        - id: auth_service  # Добавлен маршрут для аутентификации
          uri: ${AUTH_SERVICE_URL}
          predicates:
            - Path=/api/auth/**

        - id: task_api_docs
          uri: ${TASK_SERVICE_URL}
          predicates:
            - Path=/aggregate/task-service/api-docs

        - id: habit_api_docs
          uri: ${HABIT_SERVICE_URL}
          predicates:
            - Path=/aggregate/habit-service/api-docs

      httpclient:
        wiretap: true  # Для отладки
      metrics:
        enabled: true

  web:
    resources:
      add-mappings: false

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: Task Service
        url: /aggregate/task-service/api-docs
      - name: Habit Service
        url: /aggregate/habit-service/api-docs
      - name: Auth Service
        url: /aggregate/auth-service/api-docs

  api-docs:
    path: /api-docs

management:
  endpoint:
    circuitbreakerevents:
      enabled: true
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    tags:
      application: ${spring.application.name}

resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 100
        permittedNumberOfCallsInHalfOpenState: 5
        slowCallDurationThreshold: 4s
        slowCallRateThreshold: 90
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        minimumNumberOfCalls: 10
    instances:
      taskServiceCircuitBreaker:
        baseConfig: default
        waitDurationInOpenState: 20s
      habitServiceCircuitBreaker:
        baseConfig: default
        waitDurationInOpenState: 30s
  timelimiter:
    configs:
      default:
        timeout-duration: 3s
  retry:
    configs:
      default:
        max-attempts: 3
        wait-duration: 2s

server:
  port: ${GATEWAY_PORT}
  forward-headers-strategy: framework  # Важно для передачи заголовков